### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zXdj2dFGAwfG2r5gAsgfZXGH** [Flashyyyyyy/btditt-paste#1]
Starts loading then says:
ss.dwCurrentState == SERVICE_STOPPED

opens up a window that says:
StartServiceA failed with error 2: The system cannot find the file specified. as well
any ideas?

also don't mind my username.

**Comment by Flashyyyyyy** [comment]
It is not the full source code, it is missing some libaries, binaries and includes.

**Comment by zXdj2dFGAwfG2r5gAsgfZXGH** [comment]
Can you give me exactly what's missing from it, cause im really intimidated my it to be fair.
I've set my mind into checking out how it is, cause i see some interesting features.

**Comment by Flashyyyyyy** [comment]
If you compiled it with any errors it should work, if not the code is outdated, does not work anymore or then it needs updating
